- platform: manual
  name: Home Alarm Old
  unique_id: home_alarm_old
  code: !secret alarm_code
  code_arm_required: false
  arming_states:
    - armed_away
    - armed_home
  # Time it stays in triggered state
  trigger_time: 300
  disarmed:
    trigger_time: 0
  armed_home:
    delay_time: 0
    arming_time: 0
  armed_away:
    delay_time: 50
    arming_time: 48
