- platform: wyzesense
  device: auto

- platform: command_line
  name: Earth Nginx/PHP Working
  command: "curl -m 2 -s https://earth.erdely.in/phptest.php | grep '^PHP is working!' || echo 'PHP is not working!'"
  #device_class: connectivity
  payload_on: "PHP is working!"
  payload_off: "PHP is not working!"

- platform: command_line
  name: Nginx Proxy Manager Working
  command: "curl -s -f -m 2 -w %{http_code} -o /dev/null https://npm.erdely.in | grep '^200$' || echo 1"
  #device_class: connectivity
  payload_on: "200"
  payload_off: "1"

- platform: ping
  name: Google
  host: 8.8.8.8
  scan_interval: 15
  count: 4

- platform: ping
  name: Earth
  host: 192.168.25.54
  scan_interval: 15
  count: 4

- platform: ping
  name: Outside Christmas Lights
  host: 192.168.26.163
  scan_interval: 15
  count: 4

- platform: ping
  name: Mike's Pixel 6 Pro
  host: 192.168.25.131
  scan_interval: 15
  count: 4

- platform: ping
  name: Holly's Pixel 5
  host: 192.168.25.133
  scan_interval: 15
  count: 4

- platform: ping
  name: God Damn TV Ping
  host: 192.168.25.162
  scan_interval: 15
  count: 4

- platform: ping
  name: Bedroom TV Ping
  host: 192.168.25.160
  scan_interval: 15
  count: 4

- name: OctoPrint Camera Status
  platform: command_line
  command: '/usr/bin/ssh -a -o UserKnownHostsFile=/config/.ssh/known_hosts -i /config/.ssh/homeassistant ha@carpo.erdely.in camera_status'
  payload_on: 'Camera is streaming'
  payload_off: 'Camera is off'

- name: Bitwarden Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state a0d7b954_bitwarden'
  payload_on: 'on'
  payload_off: 'off'

- name: Frigate Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state ccab4aaf_frigate'
  payload_on: 'on'
  payload_off: 'off'

- name: Google Backup Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state cebe7a76_hassio_google_drive_backup'
  payload_on: 'on'
  payload_off: 'off'

- name: MariaDB Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state core_mariadb'
  payload_on: 'on'
  payload_off: 'off'

- name: MQTT Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state core_mosquitto'
  payload_on: 'on'
  payload_off: 'off'

- name: NginxProxyMgr Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state a0d7b954_nginxproxymanager'
  payload_on: 'on'
  payload_off: 'off'

- name: Signal Add-On Running
  platform: command_line
  device_class: running
  #command: '/config/bin/check_signal_addon'
  command: '/config/bin/check_addon_state 1315902c_signal_messenger'
  payload_on: 'on'
  payload_off: 'off'

- name: SSH Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state a0d7b954_ssh'
  payload_on: 'on'
  payload_off: 'off'

- name: TasmoBackup Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state 6a15710b_tasmobackup'
  payload_on: 'on'
  payload_off: 'off'

- name: Unifi Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state a0d7b954_unifi'
  payload_on: 'on'
  payload_off: 'off'

- name: Wireguard Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state a0d7b954_wireguard'
  payload_on: 'on'
  payload_off: 'off'

- name: Zigbee2MQTT Add-On Running
  platform: command_line
  device_class: running
  command: '/config/bin/check_addon_state 45df7312_zigbee2mqtt'
  payload_on: 'on'
  payload_off: 'off'

- name: Garage Door Cam Status
  platform: command_line
  device_class: garage_door
  command: '/config/bin/get_garage_door_state'
  payload_on: 'on'
  payload_off: 'off'
  scan_interval: 15

- name: New SSL Cert Available
  platform: command_line
  command: '/config/bin/check_ssl_renewed'
  payload_on: 'on'
  payload_off: 'off'

- name: New NPM SSL Cert Available
  platform: command_line
  command: '/config/bin/check_ssl_renewed_npm'
  payload_on: 'on'
  payload_off: 'off'

- name: Christmas Lights Should Be On
  platform: command_line
  command: '/config/bin/xmas_lights'
  payload_on: 'on'
  payload_off: 'off'

- name: New TV Show List Ready
  platform: command_line
  command: 'test -f /config/.newtvshowfile && echo on || echo off'
  payload_on: 'on'
  payload_off: 'off'

- platform: workday
  country: US
