- platform: wyzesense
  device: auto

- platform: ping
  name: Google
  host: 8.8.8.8
  scan_interval: 15
  count: 4

- platform: ping
  name: Earth
  host: 192.168.25.54
  scan_interval: 15
  count: 4

- platform: ping
  name: Outside Christmas Lights
  host: 192.168.26.163
  scan_interval: 15
  count: 4

- platform: ping
  name: Mike's Pixel 7 Pro
  host: 192.168.25.131
  scan_interval: 15
  count: 4

- platform: ping
  name: Holly's Pixel 5
  host: 192.168.25.133
  scan_interval: 15
  count: 4

- platform: ping
  name: God Damn TV Ping
  host: 192.168.27.142
  scan_interval: 15
  count: 4

- platform: ping
  name: Bedroom TV Wifi Ping
  host: 192.168.27.140
  scan_interval: 15
  count: 4

- platform: ping
  name: Bedroom TV Wired Ping
  host: 192.168.27.141
  scan_interval: 15
  count: 4

- platform: ping
  name: WyzeCam
  host: 192.168.27.100
  scan_interval: 15
  count: 4
