- name: Chimney Gate
  platform: mqtt
  state_topic: stat/chimney_gate/RESULT
  value_template: '{{value_json.POWER}}'
  payload_off: 'OFF'
  payload_on: 'ON'
  device_class: opening
  unique_id: chimney_gate
  device:
    identifiers:
      - 'chimney_gate'
    name: chimney_gate
    manufacturer: Tasmota

- platform: ping
  name: Google
  host: 8.8.8.8
  scan_interval: 15
  count: 4

- platform: ping
  name: Outside Christmas Lights
  host: 192.168.25.225
  scan_interval: 15
  count: 4

- platform: ping
  name: Mike Bench Switch
  host: 192.168.25.198
  scan_interval: 15
  count: 4

- platform: ping
  name: Mike's Pixel 4a
  host: 192.168.25.174
  scan_interval: 15
  count: 4

- platform: ping
  name: Holly's Pixel 3
  host: 192.168.25.205
  scan_interval: 15
  count: 4

- platform: rest
  name: Home Assistant Configuration Check
  resource: "https://ha.erdely.in:38123/api/config/core/check_config"
  method: POST
  headers:
    Authorization: !secret mike_long_lived_check_command
    Content-Type: application/json
  device_class: problem
  value_template: >-
    {% if value_json.result == 'valid' %}
      Off
    {% else %}
      On
    {% endif %}

- name: New SSL Cert Available
  platform: command_line
  command: '/config/bin/check_ssl_renewed'
  payload_on: 'on'
  payload_off: 'off'

- name: New NPM SSL Cert Available
  platform: command_line
  command: '/config/bin/check_ssl_renewed_npm'
  payload_on: 'on'
  payload_off: 'off'

- name: Christmas Lights Should Be On
  platform: command_line
  command: '/config/bin/xmas_lights'
  payload_on: 'on'
  payload_off: 'off'

- name: New TV Show List Ready
  platform: command_line
  command: 'test -f /config/.newtvshowfile && echo on || echo off'
  payload_on: 'on'
  payload_off: 'off'

- platform: workday
  country: US
