- name: Chimney Gate
  platform: mqtt
  state_topic: stat/chimney_gate/RESULT
  value_template: '{{value_json.POWER}}'
  payload_off: 'OFF'
  payload_on: 'ON'
  device_class: opening
  unique_id: chimney_gate
  device:
    identifiers:
      - 'chimney_gate'
    name: chimney_gate
    manufacturer: Tasmota

- platform: ping
  name: Google
  host: 8.8.8.8
  scan_interval: 15
  count: 4

- platform: ping
  name: Outside Christmas Lights
  host: 192.168.25.225
  scan_interval: 15
  count: 4

- platform: ping
  name: Mike Bench Switch
  host: 192.168.25.198
  scan_interval: 15
  count: 4

- platform: ping
  name: Mike's Pixel 6 Pro
  host: 192.168.25.131
  scan_interval: 15
  count: 4

- platform: ping
  name: Holly's Pixel 5
  host: 192.168.25.133
  scan_interval: 15
  count: 4

- name: OctoPrint Camera Status
  platform: command_line
  command: '/usr/bin/ssh -a -o UserKnownHostsFile=/config/.ssh/known_hosts -i /config/.ssh/homeassistant ha@carpo.erdely.in camera_status'
  payload_on: 'Camera is streaming'
  payload_off: 'Camera is off'

- name: Garage Door Cam Status
  platform: command_line
  device_class: garage_door
  command: '/config/bin/get_garage_door_state'
  payload_on: 'on'
  payload_off: 'off'
  scan_interval: 15

- name: New SSL Cert Available
  platform: command_line
  command: '/config/bin/check_ssl_renewed'
  payload_on: 'on'
  payload_off: 'off'

- name: New NPM SSL Cert Available
  platform: command_line
  command: '/config/bin/check_ssl_renewed_npm'
  payload_on: 'on'
  payload_off: 'off'

- name: Christmas Lights Should Be On
  platform: command_line
  command: '/config/bin/xmas_lights'
  payload_on: 'on'
  payload_off: 'off'

- name: New TV Show List Ready
  platform: command_line
  command: 'test -f /config/.newtvshowfile && echo on || echo off'
  payload_on: 'on'
  payload_off: 'off'

- platform: workday
  country: US
