# Configure a default setup of Home Assistant (frontend, api, etc)
# Disable default_config so we don't have EVERYTHING pulled in

default_config:
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
script secret: !include scripts/scripts_with_secrets.yaml

binary_sensor: !include binary_sensor.yaml
command_line: !include command_line.yaml
frontend: !include frontend.yaml
homeassistant: !include homeassistant.yaml
http: !include http.yaml
input_select: !include input_select.yaml
logbook: !include logbook.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
recorder: !include recorder.yaml
rest_command: !include rest_command.yaml
sensor: !include sensor.yaml
shell_command: !include shell_command.yaml
splunk: !include splunk.yaml
template: !include template.yaml
tts: !include tts.yaml

python_script:
