- platform: mqtt
  name: "Garage Door"
  unique_id: garage_door
  command_topic: "cmnd/garage_door/event"
  state_topic: "stat/garage_door/POWER"
  availability_topic: "tele/garage_door/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_open: "dooropen"
  payload_stop: "doorstop"
  payload_close: "doorclose"
  state_open: "OFF"
  state_closed: "ON"
  device_class: "garage"
  retain: false


