- platform: mqtt
  name: "Bedroom Fan"
  unique_id: "bedroom_fan"
  qos: 0
  state_topic: "stat/bedroom_fan/POWER1"
  command_topic: "cmnd/bedroom_fan/POWER1"
  availability_topic: "tele/bedroom_fan/LWT"
  percentage_state_topic: "stat/bedroom_fan/speed"
  percentage_value_template: '{{ ((value | replace("3,","")) | int(0) + 1) * 25 }}'
  percentage_command_topic: "cmnd/bedroom_fan/tuyasend4"
  percentage_command_template: "3,{{ ((value | int(0) - 1) / 25) | int(0) }}"
  preset_mode_value_template: '{{ value | replace("3,0", "low") | replace("3,1", "medium") | replace("3,2", "high") | replace("3,3", "cyclone") }}'
  preset_mode_command_topic: "cmnd/bedroom_fan/tuyasend4"
  preset_mode_command_template: '{{ value | replace("low", "3,0") | replace("medium", "3,1") | replace("high", "3,2") | replace("cyclone", "3,3") }}'
  preset_modes:
    - "low"
    - "medium"
    - "high"
    - "cyclone"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Office Fan"
  unique_id: "office_fan"
  qos: 0
  state_topic: "stat/office_fan/POWER1"
  command_topic: "cmnd/office_fan/POWER1"
  availability_topic: "tele/office_fan/LWT"
  percentage_state_topic: "stat/office_fan/speed"
  percentage_value_template: '{{ ((value | replace("3,","")) | int(0) + 1) * 25 }}'
  percentage_command_topic: "cmnd/office_fan/tuyasend4"
  percentage_command_template: "3,{{ ((value | int(0) - 1) / 25) | int(0) }}"
  preset_mode_state_topic: "stat/office_fan/speed"
  preset_mode_value_template: '{{ value | replace("3,0", "low") | replace("3,1", "medium") | replace("3,2", "high") | replace("3,3", "cyclone") }}'
  preset_mode_command_topic: "cmnd/office_fan/tuyasend4"
  preset_mode_command_template: '{{ value | replace("low", "3,0") | replace("medium", "3,1") | replace("high", "3,2") | replace("cyclone", "3,3") }}'
  preset_modes:
    - "low"
    - "medium"
    - "high"
    - "cyclone"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
