- platform: mqtt
  name: "Bedroom Fan"
  unique_id: "bedroom_fan"
  qos: 0
  state_topic: "stat/bedroom_fan/POWER1"
  command_topic: "cmnd/bedroom_fan/POWER1"
  availability_topic: "tele/bedroom_fan/LWT"
  percentage_state_topic: "stat/office_fan/speed"
  percentage_value_template: '{{ ((value | replace("3,","")) | int + 1) * 25 }}'
  percentage_command_topic: "cmnd/office_fan/tuyasend4"
  percentage_command_template: "3,{{ ((value | int - 1) / 25) | int }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Office Fan"
  unique_id: "office_fan"
  qos: 0
  state_topic: "stat/office_fan/POWER1"
  command_topic: "cmnd/office_fan/POWER1"
  availability_topic: "tele/office_fan/LWT"
  percentage_state_topic: "stat/office_fan/speed"
  percentage_value_template: '{{ ((value | replace("3,","")) | int + 1) * 25 }}'
  percentage_command_topic: "cmnd/office_fan/tuyasend4"
  percentage_command_template: "3,{{ ((value | int - 1) / 25) | int }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
# Alternative
#  - platform: mqtt
#    name: "FanTest"
#    state_topic: "stat/fantest/POWER1"
#    command_topic: "cmnd/fantest/POWER1"
#    preset_mode_state_topic: "stat/fantest/speed"
#    preset_mode_command_topic: "cmnd/fantest/tuyasend4"
#    preset_modes:
#      - "3,0"
#      - "3,1"
#      - "3,2"
#      - "3,3"
#    availability_topic: "tele/fan_test/LWT"
#    qos: 1
#    payload_available: "Online"
#    payload_not_available: "Offline"
#    payload_on: "ON"
#    payload_off: "OFF"
#    speed_range_min: 1
#    speed_range_max: 100
