- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: throughput_network_in
      arg: enp2s0
    - type: throughput_network_out
      arg: enp2s0
    - type: network_in
      arg: enp2s0
    - type: network_out
      arg: enp2s0
    - type: memory_use_percent
    - type: processor_use

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(2)  }}"

- platform: command_line
  name: Unifi AP Versions
  command: "/config/bin/get_unifi_versions"
  json_attributes:
    - data
    - error
  value_template: "{{ value_json.last_updated }}"
  scan_interval: 3600  # 1 hour

- platform: command_line
  name: OpnSense Versions
  command: "/config/bin/opnsense_snmp_versions.py"
  json_attributes:
    - core-abi
    - sys-abi
    - opnsense-update
    - plugins
  value_template: "{{ value_json.opnsense }}"
  scan_interval: 3600  # 1 hour

- platform: command_line
  name: OpnSense Package Versions
  command: >-
    /config/bin/opnsense_packages.sh
    {{ state_attr('sensor.opnsense_versions', 'sys-abi') }}
    {{ state_attr('sensor.opnsense_versions', 'core-abi') }}
  json_attributes:
    - timestamp
    - status
    - plugins
  value_template: "{{ value_json.timestamp }}"
  scan_interval: 14400  # 4 hours

- platform: command_line
  name: Dynamic DNS
  command: "/config/bin/update_ip.sh"
  json_attributes:
    - public_ip
    - dns_record
    - dynamic_hostname
    - status
    - updated_at
  value_template: "{{ value_json.public_ip }}"
  scan_interval: 900  # 15 minutes

- platform: rest
  name: FKB Control Panel
  resource: !secret fkb_deviceinfo
  value_template: "{{ value_json.batteryLevel }}"
  json_attributes:
    - deviceId
    - deviceName
    - packageName
    - batteryLevel
    - isPlugged
    - SSID
    - ip4
    - hostname4
    - wifiSignalLevel
    - screenOrientation
    - screenBrightness
    - screenLocked
    - screenOn
    - batteryTemperature
    - plugged
    - keyguardLocked
    - version
    - versionCode
    - build
    - model
    - manufacturer
    - androidVersion
    - SDK
    - webviewUA
    - foreground
    - motionDetectorStatus
    - isDeviceAdmin
    - isDeviceOwner
    - internalStorageFreeSpace
    - internalStorageTotalSpace
    - ramUsedMemory
    - ramFreeMemory
    - ramTotalMemory
    - appUsedMemory
    - appFreeMemory
    - appTotalMemory
    - scopedStorage
    - displayHeightPixels
    - displayWidthPixels
    - isMenuOpen
    - topFragmentTag
    - isInDaydream
    - appStartTime
    - isRooted
    - isLicensed
    - isInScreensaver
    - kioskLocked
    - isInForcedSleep
    - maintenaceMode
    - kioskMode
    - startURL
    - currentTabIndex
    - mqttConnected
    - currentPageUrl
    - sensorInfo
  verify_ssl: false

- platform: rest
  name: FKBMBR Control Panel
  resource: !secret fkbmbr_deviceinfo
  value_template: "{{ value_json.batteryLevel }}"
  json_attributes:
    - deviceId
    - deviceName
    - packageName
    - batteryLevel
    - isPlugged
    - SSID
    - ip4
    - hostname4
    - wifiSignalLevel
    - screenOrientation
    - screenBrightness
    - screenLocked
    - screenOn
    - batteryTemperature
    - plugged
    - keyguardLocked
    - version
    - versionCode
    - build
    - model
    - manufacturer
    - androidVersion
    - SDK
    - webviewUA
    - foreground
    - motionDetectorStatus
    - isDeviceAdmin
    - isDeviceOwner
    - internalStorageFreeSpace
    - internalStorageTotalSpace
    - ramUsedMemory
    - ramFreeMemory
    - ramTotalMemory
    - appUsedMemory
    - appFreeMemory
    - appTotalMemory
    - scopedStorage
    - displayHeightPixels
    - displayWidthPixels
    - isMenuOpen
    - topFragmentTag
    - isInDaydream
    - appStartTime
    - isRooted
    - isLicensed
    - isInScreensaver
    - kioskLocked
    - isInForcedSleep
    - maintenaceMode
    - kioskMode
    - startURL
    - currentTabIndex
    - mqttConnected
    - currentPageUrl
    - sensorInfo
  verify_ssl: false

- platform: command_line
  name: YAML LOC
  command: "find /config/ -name '*.yaml' | xargs cat | wc -l"

- platform: command_line
  name: MoCo Recycle Day
  command: bin/get_recycle_day
  # Request every 8 hours
  scan_interval: 28800

- platform: command_line
  name: Fully Kiosk Browser Version Latest
  command: bin/get_fkb_version
  scan_interval: 3600

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"

- name: Bedroom TV Next Episode
  platform: command_line
  command: 'bin/plex_nextepisode -c bin/.plexapi_rc "{{ states("input_select.bedroom_plex_show") }}"'

- name: God Damn TV Next Episode
  platform: command_line
  command: 'bin/plex_nextepisode -c bin/.plexapi_rc "{{ states("input_select.god_damn_plex_show") }}"'

- name: Living Room TV Next Episode
  platform: command_line
  command: 'bin/plex_nextepisode -c bin/.plexapi_rc "{{ states("input_select.living_room_plex_show") }}"'

- name: Office TV Next Episode
  platform: command_line
  command: 'bin/plex_nextepisode -c bin/.plexapi_rc "{{ states("input_select.office_plex_show") }}"'

- platform: command_line
  name: Holly Previous Location
  command: bin/get_prev_state person.holly_erdely "{{ states('person.holly_erdely') }}"

- platform: command_line
  name: Mike Previous Location
  command: bin/get_prev_state person.michael_erdely "{{ states('person.michael_erdely') }}"

- platform: command_line
  name: SSL Expiry Date
  command: "bin/get_ssl_expire.py"

- platform: sql
  db_url: !secret mysql_uri
  queries:
    - name: DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant_recorder" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: MB
