- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: throughput_network_in
      arg: enp2s0
    - type: throughput_network_out
      arg: enp2s0
    - type: network_in
      arg: enp2s0
    - type: network_out
      arg: enp2s0
    - type: memory_use_percent
    - type: processor_use

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(2)  }}"

- platform: mqtt
  name: Fully Kiosk Browser
  json_attributes_topic: fully/deviceInfo/32e18972-a62f66fd
  unit_of_measurement: "%"
  device_class: "battery"
  state_topic: fully/deviceInfo/32e18972-a62f66fd
  value_template: "{{ value_json.batteryLevel }}"

- platform: mqtt
  name: Fully Kiosk Browser MBR
  json_attributes_topic: fully/deviceInfo/fe195503-ca16fc27
  unit_of_measurement: "%"
  device_class: "battery"
  state_topic: fully/deviceInfo/fe195503-ca16fc27
  value_template: "{{ value_json.batteryLevel }}"

- platform: rest
  name: HA Operating System Version
  resource: "https://ha.erdely.in:38123/api/hassio/os/info"
  headers:
    Authorization: !secret mike_long_lived_check_command
    Content-Type: application/json
  value_template: "{{ value_json.data.update_available }}"
  json_attributes_path: "$.data"
  json_attributes:
    - version
    - version_latest
    - update_available

- platform: rest
  name: HA Supervisor Version
  resource: "https://ha.erdely.in:38123/api/hassio/supervisor/info"
  headers:
    Authorization: !secret mike_long_lived_check_command
    Content-Type: application/json
  value_template: "{{ value_json.data.update_available }}"
  json_attributes_path: "$.data"
  json_attributes:
    - version
    - version_latest
    - update_available

- platform: rest
  name: HA Add-Ons
  resource: "https://ha.erdely.in:38123/api/hassio/addons"
  headers:
    Authorization: !secret mike_long_lived_check_command
    Content-Type: application/json
  value_template: "{{ value_json.result }}"
  json_attributes_path: "$.data"
  json_attributes:
    - addons

- platform: command_line
  name: YAML LOC
  command: "find /config/ -name '*.yaml' | xargs cat | wc -l"

- platform: command_line
  name: MoCo Recycle Day
  command: bin/get_recycle_day
  # Request every 8 hours
  scan_interval: 28800

- platform: version
  name: home_assistant_version
  source: local

#- platform: mqtt
#  name: Assistant Relay Version
#  state_topic: "software_versions/assistant_relay"
#  value_template: "{{ value_json.version }}"

#- platform: rest
#  name: Assistant Relay Version Latest
#  resource: "https://api.github.com/repos/greghesp/assistant-relay/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name | replace('v', '') }}
#  scan_interval: 3660

#- platform: rest
#  name: Chronograf Version Latest
#  resource: "https://api.github.com/repos/influxdata/chronograf/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name }}
#  scan_interval: 3660

#- platform: mqtt
#  name: Codium Version
#  state_topic: "software_versions/codium"
#  value_template: "{{ value_json.version }}"

#- platform: rest
#  name: Codium Version Latest
#  resource: "https://api.github.com/repos/VSCodium/vscodium/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name }}
#  scan_interval: 3660

- platform: mqtt
  name: Docker Compose Version
  state_topic: "software_versions/docker_compose"
  value_template: "{{ value_json.version }}"

- platform: rest
  name: Docker Compose Version Latest
  resource: "https://api.github.com/repos/docker/compose/releases/latest"
  username: !secret github_username
  password: !secret github_secret
  value_template: >-
    {{ value_json.tag_name }}
  scan_interval: 3660

# version is above with templates
- platform: scrape
  name: Fully Kiosk Browser Version Latest
  resource: "https://www.fully-kiosk.com/en/"
  select: "a.su-button"
  value_template: "{{ value.split(' ')[6] }}"
  scan_interval: 3600

#- platform: mqtt
#  name: GitLab Version
#  state_topic: "software_versions/gitlab"
#  value_template: "{{ value_json.version }}"

#- platform: command_line
#  name: GitLab Version Latest
#  command: '/usr/bin/curl -s https://gitlab.com/gitlab-org/gitlab-foss/-/tags|/bin/grep "^Version v[0-9]"|/usr/bin/sort -nr|/usr/bin/awk -Fv "\$0!~/-rc[0-9]/{print \$2;exit}"'
#  scan_interval: 3600

#- platform: rest
#  name: Grafana Version Latest
#  resource: "https://api.github.com/repos/grafana/grafana/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name }}
#  scan_interval: 3660

#- platform: rest
#  name: InfluxDB Version Latest
#  resource: "https://api.github.com/repos/influxdata/influxdb/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name }}
#  scan_interval: 3660

- platform: mqtt
  name: Joplin Desktop Version
  state_topic: "software_versions/joplin_desktop"
  value_template: "{{ value_json.version }}"

- platform: rest
  name: Joplin Desktop Version Latest
  resource: "https://api.github.com/repos/laurent22/joplin/releases/latest"
  username: !secret github_username
  password: !secret github_secret
  value_template: >-
    {{ value_json.tag_name }}
  scan_interval: 3660

#- platform: rest
#  name: Kapacitor Version Latest
#  resource: "https://api.github.com/repos/influxdata/kapacitor/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name }}
#  scan_interval: 3660

#- platform: mqtt
#  name: Mosquitto Version
#  state_topic: "$SYS/broker/version"
#  value_template: "v{{ value.split()[2] }}"

#- platform: scrape
#  name: Mosquitto Version Latest
#  resource: "https://mosquitto.org/download/"
#  select: "li a"
#  value_template: "{{ value | replace('mosquitto-', 'v') | replace('.tar.gz', '') }}"
#  scan_interval: 3660

- platform: scrape
  name: Nagios Version
  resource: "https://nagios.erdely.in/main.php"
  select: "div.version"
  value_template: "{{ value | replace('Version ', '') }}"
  scan_interval: 3600

- platform: scrape
  name: Nagios Version Latest
  resource: "https://www.nagios.org/checkforupdates/?product=nagioscore"
  select: "div.col-xs-12"
  value_template: "{{ value.split(' ')[21] }}"
  scan_interval: 3600

# OpenBSD Mars Version is a template sensor above
- platform: command_line
  name: OpenBSD Mars Version Latest
  command: bin/get_openbsd_patch
  scan_interval: 7320

#- platform: mqtt
#  name: PiHole Version
#  state_topic: "software_versions/pihole"
#  value_template: "{{ value_json.version }}"
#- platform: rest
#  name: PiHole Version Latest
#  resource: "https://api.github.com/repos/pi-hole/pi-hole/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name }}
#  scan_interval: 3660
#
- platform: rest
  name: Plex Version
  resource: !secret plex_server_info
  value_template: '{{ value_json["MediaContainer"]["@version"].split("-")[0] }}'
  scan_interval: 3600
  #json_attributes_path: "$.MediaContainer"
  #json_attributes:
  #  - version

- platform: mqtt
  name: Proton GE Version
  state_topic: "software_versions/proton_ge"
  value_template: "{{ value_json.version }}"

- platform: rest
  name: Proton GE Version Latest
  resource: "https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest"
  username: !secret github_username
  password: !secret github_secret
  value_template: >-
    {{ value_json.tag_name }}
  scan_interval: 3660

- platform: rest
  name: Plex Version Latest
  resource: "https://plex.tv/pms/downloads/5.json?channel=plexpass"
  value_template: '{{ value_json["computer"]["Linux"].version.split("-")[0] }}'
  scan_interval: 3600

- platform: mqtt
  name: Rclone Version
  state_topic: "software_versions/rclone"
  value_template: "{{ value_json.version }}"

- platform: rest
  name: Rclone Version Latest
  resource: "https://api.github.com/repos/rclone/rclone/releases/latest"
  username: !secret github_username
  password: !secret github_secret
  value_template: >-
    {{ value_json.tag_name }}
  scan_interval: 3660

- platform: rest
  name: Restreamer Version
  resource: "https://restreamer.erdely.in/frontdoorcam/v1/version"
  value_template: "v{{ value_json.version }}"
  scan_interval: 3600

- platform: rest
  name: Restreamer Version Latest
  resource: "https://api.github.com/repos/datarhei/restreamer/releases/latest"
  username: !secret github_username
  password: !secret github_secret
  value_template: "{{ value_json.tag_name }}"
  scan_interval: 3660

#- platform: mqtt
#  name: TasmoBackup Version
#  state_topic: "software_versions/tasmobackup"
#  value_template: "{{ value_json.version }}"

#- platform: rest
#  name: TasmoBackup Version Latest
#  resource: "https://api.github.com/repos/danmed/TasmoBackupV1/tags"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json[0].name }}
#  scan_interval: 3660

#- platform: mqtt
#  name: Tasmota Decode Config Version
#  state_topic: "software_versions/decode_config"
#  value_template: "{{ value_json.version }}"

#- platform: rest
#  name: Tasmota Decode Config Version Latest
#  resource: "https://api.github.com/repos/tasmota/decode-config/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name }}
#  scan_interval: 3660

- platform: rest
  name: Tautulli Version Latest
  resource: "https://api.github.com/repos/Tautulli/Tautulli/releases/latest"
  username: !secret github_username
  password: !secret github_secret
  value_template: >-
    {{ value_json.tag_name }}
  scan_interval: 3660

#- platform: rest
#  name: Telegraf Version Latest
#  resource: "https://api.github.com/repos/influxdata/telegraf/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name }}
#  scan_interval: 3660

- platform: mqtt
  name: tmux Version
  state_topic: "software_versions/tmux"
  value_template: "{{ value_json.version }}"

- platform: rest
  name: tmux Version Latest
  resource: "https://api.github.com/repos/tmux/tmux/releases/latest"
  username: !secret github_username
  password: !secret github_secret
  value_template: >-
    {{ value_json.tag_name | replace('v', '') }}
  scan_interval: 3660

- platform: rest
  name: Unifi-Poller Version Latest
  resource: "https://api.github.com/repos/unifi-poller/unifi-poller/releases/latest"
  username: !secret github_username
  password: !secret github_secret
  value_template: >-
    {{ value_json.tag_name }}
  scan_interval: 3660

- platform: rest
  name: Varken Version Latest
  resource: "https://api.github.com/repos/Boerderij/Varken/releases/latest"
  username: !secret github_username
  password: !secret github_secret
  value_template: >-
    {{ value_json.tag_name }}
  scan_interval: 3660

#- platform: mqtt
#  name: vscode Code Server Version
#  state_topic: "software_versions/vscode"
#  value_template: "{{ value_json.version }}"

#- platform: rest
#  name: vscode Code Server Version Latest
#  resource: "https://api.github.com/repos/cdr/code-server/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name | replace('v', '') }}
#  scan_interval: 3660

- platform: rest
  name: Yourls Version
  resource: "https://erde.ly/ver.php"
  value_template: "{{ value_json.version }}"
  scan_interval: 3600

- platform: rest
  name: Yourls Version Latest
  resource: "https://api.github.com/repos/YOURLS/YOURLS/releases/latest"
  username: !secret github_username
  password: !secret github_secret
  value_template: >-
    {{ value_json.tag_name }}
  scan_interval: 3660

#- platform: mqtt
#  name: Zigbee2MQTT Version
#  state_topic: "software_versions/zigbee2mqtt"
#  value_template: "{{ value_json.version }}"

#- platform: rest
#  name: Zigbee2MQTT Version Latest
#  resource: "https://api.github.com/repos/Koenkk/zigbee2mqtt/releases/latest"
#  username: !secret github_username
#  password: !secret github_secret
#  value_template: >-
#    {{ value_json.tag_name | replace('v', '') }}
#  scan_interval: 3660

- platform: mqtt
  name: Printer Ink
  state_topic: "ink2mqtt/192.168.25.25"
  value_template: "{{ value_json.printer }}"
  json_attributes_topic: "ink2mqtt/192.168.25.25"

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"

- name: Bedroom TV Next Episode
  platform: command_line
  command: 'bin/plex_nextepisode -c bin/.plexapi_rc "{{ states("input_select.bedroom_plex_show") }}"'

- name: God Damn TV Next Episode
  platform: command_line
  command: 'bin/plex_nextepisode -c bin/.plexapi_rc "{{ states("input_select.god_damn_plex_show") }}"'

- name: Living Room TV Next Episode
  platform: command_line
  command: 'bin/plex_nextepisode -c bin/.plexapi_rc "{{ states("input_select.living_room_plex_show") }}"'

- name: Office TV Next Episode
  platform: command_line
  command: 'bin/plex_nextepisode -c bin/.plexapi_rc "{{ states("input_select.office_plex_show") }}"'

- platform: command_line
  name: Holly Previous Location
  command: bin/get_prev_state person.holly_erdely "{{ states('person.holly_erdely') }}"

- platform: command_line
  name: Mike Previous Location
  command: bin/get_prev_state person.michael_erdely "{{ states('person.michael_erdely') }}"

- platform: command_line
  name: SSL Expiry Date
  command: "bin/get_ssl_expire.py"

- platform: sql
  db_url: !secret mysql_uri
  queries:
    - name: DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant_recorder" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: MB
