- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: throughput_network_in
      arg: enp2s0
    - type: throughput_network_out
      arg: enp2s0
    - type: network_in
      arg: enp2s0
    - type: network_out
      arg: enp2s0
    - type: memory_use_percent
    - type: processor_use

- platform: rest
  name: FKB Control Panel
  resource: !secret fkb_deviceinfo
  value_template: "{{ value_json.batteryLevel }}"
  json_attributes:
    - deviceId
    - deviceName
    - packageName
    - batteryLevel
    - isPlugged
    - SSID
    - ip4
    - hostname4
    - wifiSignalLevel
    - screenOrientation
    - screenBrightness
    - screenLocked
    - screenOn
    - batteryTemperature
    - plugged
    - keyguardLocked
    - version
    - versionCode
    - build
    - model
    - manufacturer
    - androidVersion
    - SDK
    - webviewUA
    - foreground
    - motionDetectorStatus
    - isDeviceAdmin
    - isDeviceOwner
    - internalStorageFreeSpace
    - internalStorageTotalSpace
    - ramUsedMemory
    - ramFreeMemory
    - ramTotalMemory
    - appUsedMemory
    - appFreeMemory
    - appTotalMemory
    - scopedStorage
    - displayHeightPixels
    - displayWidthPixels
    - isMenuOpen
    - topFragmentTag
    - isInDaydream
    - appStartTime
    - isRooted
    - isLicensed
    - isInScreensaver
    - kioskLocked
    - isInForcedSleep
    - maintenaceMode
    - kioskMode
    - startURL
    - currentTabIndex
    - mqttConnected
    - currentPageUrl
    - sensorInfo
  verify_ssl: false

- platform: rest
  name: FKBMBR Control Panel
  resource: !secret fkbmbr_deviceinfo
  value_template: "{{ value_json.batteryLevel }}"
  json_attributes:
    - deviceId
    - deviceName
    - packageName
    - batteryLevel
    - isPlugged
    - SSID
    - ip4
    - hostname4
    - wifiSignalLevel
    - screenOrientation
    - screenBrightness
    - screenLocked
    - screenOn
    - batteryTemperature
    - plugged
    - keyguardLocked
    - version
    - versionCode
    - build
    - model
    - manufacturer
    - androidVersion
    - SDK
    - webviewUA
    - foreground
    - motionDetectorStatus
    - isDeviceAdmin
    - isDeviceOwner
    - internalStorageFreeSpace
    - internalStorageTotalSpace
    - ramUsedMemory
    - ramFreeMemory
    - ramTotalMemory
    - appUsedMemory
    - appFreeMemory
    - appTotalMemory
    - scopedStorage
    - displayHeightPixels
    - displayWidthPixels
    - isMenuOpen
    - topFragmentTag
    - isInDaydream
    - appStartTime
    - isRooted
    - isLicensed
    - isInScreensaver
    - kioskLocked
    - isInForcedSleep
    - maintenaceMode
    - kioskMode
    - startURL
    - currentTabIndex
    - mqttConnected
    - currentPageUrl
    - sensorInfo
  verify_ssl: false

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"

- platform: sql
  db_url: !secret mysql_uri
  queries:
    - name: DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant_recorder" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: MB
