#- platform: mqtt
#  name: Siren
#  unique_id: siren
#  command_topic: "cmnd/siren/POWER1"
#  state_topic: "stat/siren/POWER1"
#  availability_topic: "tele/siren/LWT"
#  state_on: "ON"
#  state_off: "OFF"
#  payload_on: "1"
#  payload_off: "0"
#  payload_available: "Online"
#  payload_not_available: "Offline"
#  retain: false

- platform: template
  switches:
    outside_xmas:
      friendly_name: "Outside Christmas Lights"
      icon_template: mdi:string-lights
      value_template: '{{ states("group.outside_xmas") }}'
      turn_on:
        - service: homeassistant.turn_on
          entity_id: switch.outdoor_strip_p1
        - service: homeassistant.turn_on
          entity_id: switch.outdoor_strip_p2
        - service: homeassistant.turn_on
          entity_id: switch.outdoor_strip_p3
      turn_off:
        - service: homeassistant.turn_off
          entity_id: switch.outdoor_strip_p1
        - service: homeassistant.turn_off
          entity_id: switch.outdoor_strip_p2
        - service: homeassistant.turn_off
          entity_id: switch.outdoor_strip_p3

    bedroom_tv:
      friendly_name: "Bedroom TV"
      icon_template: mdi:television
      value_template: >-
        {% if states('binary_sensor.bedroom_tv_ping') != 'on' %}
          off
        {% else %}
          on
        {% endif %}
      turn_on:
        - service: mqtt.publish
          data:
            topic: cmnd/bedroom_tv_remote/backlog
            payload: 'irsend {"Protocol":"SAMSUNG","Bits":32,"Data":"0xe0e09966"}'
        - delay: '2'
        - service: homeassistant.update_entity
          target:
            entity_id: binary_sensor.bedroom_tv_ping
      turn_off:
        - service: media_player.select_source
          entity_id: media_player.bedroom_roku
          data:
            source: Home
        - service: mqtt.publish
          data:
            topic: cmnd/bedroom_tv_remote/backlog
            payload: 'irsend {"Protocol":"SAMSUNG","Bits":32,"Data":"0xe0e019e6"}'
        - service: python_script.set_state
          data:
            entity_id: binary_sensor.bedroom_tv_ping
            state: off

    god_damn_tv:
      friendly_name: "God Damn TV"
      icon_template: mdi:television
      value_template: >-
        {% if states('binary_sensor.god_damn_tv_ping') != 'on' %}
          off
        {% else %}
          on
        {% endif %}
      turn_on:
        - service: mqtt.publish
          data:
            topic: cmnd/god_damn_tv_remote/backlog
            payload: 'irsend {"Protocol":"SAMSUNG","Bits":32,"Data":"0xe0e09966"}'
        - delay: '2'
        - service: homeassistant.update_entity
          target:
            entity_id: binary_sensor.god_damn_tv_ping
      turn_off:
        - service: media_player.select_source
          entity_id: media_player.god_damn_roku
          data:
            source: Home
        - service: mqtt.publish
          data:
            topic: cmnd/god_damn_tv_remote/backlog
            payload: 'irsend {"Protocol":"SAMSUNG","Bits":32,"Data":"0xe0e019e6"}'
        - service: python_script.set_state
          data:
            entity_id: binary_sensor.god_damn_tv_ping
            state: off

    living_room_tv:
      friendly_name: "Living Room TV"
      icon_template: mdi:television
      value_template: >-
        {% if states('media_player.living_room_roku_tv') == "off" or states('media_player.living_room_roku_tv') == "standby" %}
          off
        {% else %}
          on
        {% endif %}
      turn_on:
        - service: media_player.turn_on
          target:
            entity_id: media_player.living_room_roku_tv
      turn_off:
        - service: media_player.select_source
          entity_id: media_player.living_room_roku_tv
          data:
            source: Home
        - delay: 1
        - service: media_player.turn_off
          target:
            entity_id: media_player.living_room_roku_tv

    office_tv:
      friendly_name: "Office TV"
      icon_template: mdi:television
      value_template: >-
        {% if states('sensor.office_tv_plug_power') | float(0) < 5 %}
          off
        {% else %}
          on
        {% endif %}
      turn_on:
        - condition: template
          value_template: '{{ states("sensor.office_tv_plug_power") | float(0) < 5 }}'
        - service: homeassistant.turn_on
          entity_id: switch.office_tv_plug
        - delay: '2'
        - service: mqtt.publish
          data:
            topic: cmnd/office_tv_remote/backlog
            payload: 'irsend {"Protocol":"NEC","Bits":32,"Data":"0xCC33C13E","DataLSB":"0x33CC837C","Repeat":0}'
      turn_off:
        - condition: template
          value_template: '{{ states("sensor.office_tv_plug_power") | float(0) >= 5 }}'
        - service: media_player.select_source
          entity_id: media_player.office_roku
          data:
            source: Home
        - service: mqtt.publish
          data:
            topic: cmnd/office_tv_remote/backlog
            payload: 'irsend {"Protocol":"NEC","Bits":32,"Data":"0xCC33C13E","DataLSB":"0x33CC837C","Repeat":0}'

    downstairs:
      friendly_name: "Downstairs"
      value_template: >-
        {% if is_state('switch.family_room', 'on') or
              is_state('switch.den', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.god_damn_switch, switch.god_damn_tv
      turn_off:
        - service: homeassistant.turn_off
          entity_id: switch.family_room, switch.den

    family_room:
      friendly_name: "Family Room"
      value_template: >-
        {% if is_state('switch.god_damn_tv', 'on') or
              is_state('light.god_damn_switch', 'on') or
              is_state('switch.fireplace_light', 'on') or
              is_state('switch.three_headed_lamp', 'on') or
              is_state('switch.christmas_tree', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.god_damn_switch
      turn_off:
        - service: homeassistant.turn_off
          entity_id: switch.god_damn_tv, light.god_damn_switch, switch.fireplace_light, switch.three_headed_lamp, switch.christmas_tree

    den:
      friendly_name: "Den"
      value_template: >-
        {% if is_state('light.den_overhead_light', 'on') or
              is_state('light.laundry_room_light', 'on') or
              is_state('light.powder_room_light', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.den_overhead_light, light.laundry_room_light
      turn_off:
        - service: homeassistant.turn_off
          entity_id: light.den_overhead_light, light.laundry_room_light, light.powder_room_light

            # is_state('light.guest_room_light', 'on') or
    upstairs:
      friendly_name: "Upstairs"
      value_template: >-
        {% if is_state('light.hallway_light', 'on') or
              is_state('switch.bedroom', 'on') or
              is_state('switch.office', 'on') or
              is_state('switch.hall_bath', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.hallway_light, light.bedroom_fan_light, light.master_bath_light, light.office_fan_light, light.hall_bath_light #, light.guest_room_light
      turn_off:
        - service: homeassistant.turn_off
          entity_id: light.hallway_light, switch.bedroom, switch.office, switch.hall_bath #, light.guest_room_light

    bedroom:
      friendly_name: "Bedroom"
      value_template: >-
        {% if is_state('light.bedroom_fan_light', 'on') or
              is_state('fan.office_fan', 'on') or
              is_state('light.master_bath_light', 'on') or
              is_state('switch.master_bath_fan', 'on') or
              is_state('switch.bedroom_tv', 'on') or
              is_state('light.dresser_lamp', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.dresser_lamp
      turn_off:
        - service: homeassistant.turn_off
          entity_id: light.dresser_lamp, switch.bedroom_tv, light.bedroom_fan_light, light.master_bath_light, switch.master_bath_fan

    hall_bath:
      friendly_name: "Hall Bath"
      value_template: >-
        {% if is_state('light.hall_bath_light', 'on') or
              is_state('switch.hall_bath_fan', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.hall_bath_light
      turn_off:
        - service: homeassistant.turn_off
          entity_id: light.hall_bath_light, switch.hall_bath_fan

    office:
      friendly_name: "Office"
      value_template: >-
        {% if is_state('switch.office_tv', 'on') or
              is_state('light.office_fan_light', 'on') or
              is_state('fan.office_fan', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.office_fan_light
      turn_off:
        - service: homeassistant.turn_off
          entity_id: switch.office_tv, light.office_fan_light
        - service: homeassistant.turn_on
          entity_id: switch.mercury_screensaver, switch.venus_screensaver

    kitchen:
      friendly_name: "Kitchen"
      value_template: >-
        {% if is_state('light.kitchen_table_light', 'on') or
              is_state('light.kitchen_overhead_light', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.kitchen_table_light
      turn_off:
        - service: homeassistant.turn_off
          entity_id: light.kitchen_table_light, light.kitchen_overhead_light

    living_room:
      friendly_name: "Living Room"
      value_template: >-
        {% if is_state('switch.living_room_tv', 'on') or
              is_state('light.near_black_lamp', 'on') or
              is_state('light.far_black_lamp', 'on') or
              is_state('light.white_lamp', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.near_black_lamp
      turn_off:
        - service: homeassistant.turn_off
          entity_id: switch.living_room_tv, light.near_black_lamp, light.far_black_lamp, light.white_lamp

    middle_level:
      friendly_name: "Middle Level"
      value_template: >-
        {% if is_state('switch.kitchen', 'on') or
              is_state('switch.living_room', 'on') or
              is_state('light.foyer_light', 'on') or
              is_state('light.dining_room_overhead_light', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: switch.kitchen, light.near_black_lamp, light.far_black_lamp, light.white_lamp, light.foyer_light, light.dining_room_overhead_light
      turn_off:
        - service: homeassistant.turn_off
          entity_id: switch.kitchen, switch.living_room, light.foyer_light, light.dining_room_overhead_light

    outside:
      friendly_name: "Outside"
      value_template: >-
        {% if is_state('switch.front_yard', 'on') or
              is_state('switch.back_yard', 'on') or
              is_state('switch.garage', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: switch.front_yard, switch.back_yard, switch.garage
      turn_off:
        - service: homeassistant.turn_off
          entity_id: switch.front_yard, switch.back_yard, switch.garage

    front_yard:
      friendly_name: "Front Yard"
      value_template: >-
        {% if is_state('light.front_porch_light', 'on') or
              is_state('switch.outside_xmas', 'on') or
              is_state('light.outside_garage_lights', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.outside_christmas_lights
                state: 'on'
            sequence:
              - service: homeassistant.turn_on
                data: {}
                entity_id: switch.outside_xmas
        default:
          - service: homeassistant.turn_on
            data: {}
            entity_id: 'light.front_porch_light, light.outside_garage_lights'
      turn_off:
        - service: homeassistant.turn_off
          entity_id: switch.outside_xmas, light.front_porch_light, light.outside_garage_lights

    back_yard:
      friendly_name: "Back Yard"
      value_template: >-
        {% if is_state('light.back_porch_light', 'on') or
              is_state('switch.shed_lamp', 'on') or
              is_state('switch.flood_light', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.back_porch_light, switch.shed_lamp, switch.flood_light
      turn_off:
        - service: homeassistant.turn_off
          entity_id: light.back_porch_light, switch.shed_lamp, switch.flood_light

    garage:
      friendly_name: "Garage"
      value_template: >-
        {% if is_state('light.bench_light', 'on') or
              is_state('light.middle_garage_light', 'on') or
              is_state('light.far_garage_light', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: light.bench_light, light.middle_garage_light, light.far_garage_light
      turn_off:
        - service: homeassistant.turn_off
          entity_id: light.bench_light, light.middle_garage_light, light.far_garage_light

    indoor_christmas_lights:
      friendly_name: "Indoor Christmas Lights"
      value_template: >-
        {% if is_state('switch.dining_room_christmas_lights', 'on') or
              is_state('switch.mantle_lights', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      turn_on:
        - service: homeassistant.turn_on
          entity_id: switch.dining_room_christmas_lights, switch.mantle_lights
      turn_off:
        - service: homeassistant.turn_off
          entity_id: switch.dining_room_christmas_lights, switch.mantle_lights

    oven:
      friendly_name: Oven
      value_template: "{{ states('binary_sensor.oven_is_on') }}"
      turn_on: []
      turn_off: []
